### ISSUE TITLE
Infer Schema failing for this file

### ISSUE THREAD

**Issue by grahamwren** [SamedhG/sorer#1]
Not sure what's wrong with this file, it's generated based on the value spec in the assignment and only includes `STRING`, `INT`, `FLOAT` values. Our implementation of sorer correctly reports the column types however when running with this repo we get no fields in the schema:

```bash
$  sorer cargo run --release -- -f big_file_0.sor -print_col_idx 0 0
    Finished release [optimized] target(s) in 0.11s
     Running `target/release/sorer -f big_file_0.sor -print_col_idx 0 0`
Ok(2.018ms)
Error: There are only 0 fields in the schema
```

Testing with https://github.com/SamedhG/sorer/commit/af57f21

Test file: [big_file_0.sor.zip](https://github.com/SamedhG/sorer/files/4162305/big_file_0.sor.zip)

**Comment by SamedhG** [comment]
I see a lot of unquoted strings with spaces in them, we discard lines with these errors, As far as I remember from the spec Unquoted strings cannot have spaces

**Comment by SamedhG** [comment]
from the assignment page: "Strings can be written either as a sequences of characters without spaces or as a double quote delimited sequence of characters with spaces. Line breaks are not allowed in strings. "

**Comment by SamedhG** [comment]
Also the bug with large numbers that you mentioned in class was fixed. Since "an INTEGER can be any C++ int value" we decided that a large number is not an Int, this will then get passed to the float parser, the built in float parser will return an inf for large numbers, currently we deem that as acceptable behavior, if this in the future feels unacceptable, we can easily discard infs returned by the float parser and parse it as a String.

**Comment by grahamwren** [comment]
Yep, the spaces look like the issue. I'll update our file generator.

And yes, that seems like reasonable behavior barring the edge case of a "user" deciding to store values outside of the `INT`/`FLOAT` max in a string column. Though this is fairly common in database tables.
