### ISSUE TITLE
Add a C API to the program

### ISSUE THREAD

**Issue by SamedhG** [SamedhG/sorer#2]
A C API Would be ideal to make it easy for peoople in the class to use this library. 
This blog post provides pretty detailed information on how to do this simply: https://www.greyblake.com/blog/2017-08-10-exposing-rust-library-to-c/
Opening issue for further discussions on this topic.

**Comment by SamedhG** [comment]
We have begun implementation for this, in a branch however since details are currently unclear we are trying to avoid wasted effort

**Comment by tomharmon** [comment]
Per the instructors response [here](https://piazza.com/class/k51bluky59n2jr?cid=663), for assignment 5 the integration with sorer is not necessary and it will be easier to use a [csv parser](https://codingboost.com/parsing-csv-files-in-c#read-and-process-the-file-as-a-csv-file) (and [atoi](http://www.cplusplus.com/reference/cstdlib/atoi/)) for this assignment, partly due to the lack of clarity on how the management wants the `sorer` to integrate with the `DataFrame` API). 

We are going to consult with the management and then post updates here.

**Comment by tomharmon** [comment]
Actually, according to this newer [post](https://piazza.com/class/k51bluky59n2jr?cid=680), reading a data file in is not necessary. You can just make a for loop to add all of your data.

**Comment by tomharmon** [comment]
We are thinking of two options:
1. Implementing the `DataFrame` API given to us by the professors in Rust and providing a `dataframe.h` CwC file that calls into Rust to execute the `DataFrame` functions. This has the upside of being easier for users.
2. Providing a `sor.h` file with one function that takes `file_name`, `from`, and `len` that calls into Rust and constructs a `DataFrame` from the given file. The Rust function returns a `void*` that the `sor.h` function casts to a `DataFrame*` and returns the casted object. This has a few downsides, one being that everyone using our implementation would have to (recursively) have the same fields in their `DataFrame` implementation.

**Comment by tomharmon** [comment]
Vitek said we could do the first option so we are going to do that

**Comment by tomharmon** [comment]
We realized there was a slight problem with the first approach... We would have to make an FFI call from our Rust implementation of `DataFrame` to the client's implementation of their `Rower::accept` method. We're assuming this would likely be an unacceptable performance hit, though we did not test it.

Also, since the final project can now be in any language, we're likely not going to expose a C API any longer since we don't want to put in the effort and because of how hard it would be given the constraints of CwC (which most clients would likely be using, and how they would have to recursively have the same fields as us in all of their objects).
